language: java
jdk: openjdk6
script: mvn clean package
after_success:
  - cd /tmp
  - git clone https://${GH_OAUTH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME} mathematica-repl
  - cd mathematica-repl
  - cp $CI_HOME/mathematica-repl.jar .
  - git config --global user.name $GIT_AUTHOR_NAME
  - git config --global user.email $GIT_AUTHOR_EMAIL
  - git add mathematica-repl.jar
  - git commit -m "[ci skip] Committed by Travis-CI"
  - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME} 2>&1
env:
  global:
    - secure: <secure token>
    - GH_USER_NAME: dubrousky
    - GH_PROJECT_NAME: "Mathematica REPL"
    - GIT_AUTHOR_NAME: "TravisCI"
    - GIT_AUTHOR_EMAIL: "noreply@travis-ci.org"
    - CI_HOME=`pwd`/$TRAVIS_REPO_SLUG